
services:
  backend:
    build:
      context: ./backend
    container_name: tacs-backend
    ports:
      - "3000:3000"
    volumes:
      # Sincroniza tu código local con el contenedor para que tsx aplique los cambios en vivo
      - ./backend:/app
      # Evita que tu carpeta node_modules local pise la del contenedor
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"   # Puerto principal de comunicación
      - "15672:15672" # Puerto del panel de administración UI